FROM python:3 as build

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && pip install pyinstaller

COPY cddns cddns
COPY run.py .

RUN pyinstaller -F -n cddns run.py


FROM debian:bookworm-slim

COPY --from=build /app/dist/cddns /bin/cddns

ENTRYPOINT [ "cddns" ]
