name: Build Container

on:
  push:
    branches:
    - main
    paths:
    - "Dockerfile"
    - "run.py"
    - "cddns/**"
    - ".github/workflows/build.yml"
  release:
    types:
    - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Codebase
      uses: actions/checkout@v3

    - name: Login to ghcr.io
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u soup-bowl --password-stdin

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Build & Push - Development Edition
      if: ${{ github.event_name == 'push' }}
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: >
          soupbowl/cf-dynamicdns:edge,
          ghcr.io/soup-bowl/cf-dynamicdns:edge
        platforms: >
          linux/amd64,
          linux/arm64,
          linux/arm/v7

    - name: Build & Push - Production Edition
      if: ${{ github.event_name == 'release' }}
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: > 
          soupbowl/cf-dynamicdns:${{ github.event.release.tag_name }},
          soupbowl/cf-dynamicdns:latest,
          ghcr.io/soup-bowl/cf-dynamicdns:${{ github.event.release.tag_name }},
          ghcr.io/soup-bowl/cf-dynamicdns:latest
        platforms: >
          linux/amd64,
          linux/arm64,
          linux/arm/v7
